### ISSUE TITLE
Hi, sorry super new to ionic and capacitor, can we use remix with ionic?

### ISSUE THREAD

**Issue by algoflows** [ionic-team/capacitor-remix-templates#1]
Hi Ionic Team,

What an amazing repo!

Can we use this repo with other services such as Ionic and CICD deployment to appstores etc?

Bests,

Sean.

**Comment by thomasvidas** [comment]
@algoflows, yes! These starters are only the barest of bones to get Capacitor + Remix working together. You can use Ionic Framework, your CI/CD of choice, and whatever other web tools you want. If you have more questions, I'd suggest checking out the [Ionic Discord](https://discord.gg/UPYYRhtyzp) or the [Ionic Forum](https://forum.ionicframework.com).

**Comment by algoflows** [comment]
Hey @thomasvidas thanks for the response.

Couple more questions:

1. So, could use any router we wanted say the new React Location router from tanstack (not with remix) just general question? If we use another router, what are we missing if we don't use the Ionic Router that wraps react router? I am still confused at the divide between ionic framework/cli and then ionic visual components?

2. I tried the remix starter templates, but the remix app kept crashing on importing capacitor plugins...

3. How does capacitor use remix as its SSR framework, can we use remix actions etc when data loading?

4. A few more examples applications would be helpful :)

Thanks in advance...

**Comment by thomasvidas** [comment]
@algoflows these questions are better answered on the [Ionic forum](forum.ionicframework.com) or on the Ionic Discord. GitHub issues aren't the right place for questions like these
